services:
  db:
    image: postgres:16
    container_name: sample-container-db
    environment:
      POSTGRES_USER: sample-user
      POSTGRES_PASSWORD: sample-password
      POSTGRES_DB: sample-db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: